'use client';
import { useEffect } from 'react';
import Head from 'next/head';

import { useDispatch } from 'react-redux';

import { PlayingTemplate } from '@ms/components/templates';
import { ECardStatus } from '@ms/enums';
import { startGameAction } from '@ms/redux/slices/gamePlaySlice';
import { TCard } from '@ms/types';

const Home = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    const cards: TCard[] = [
      {
        name: 'thanos',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
      {
        name: 'ebony-maw',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
      {
        name: 'pig',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
      {
        name: 'demon',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
      {
        name: 'demon',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
      {
        name: 'demon',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
      {
        name: 'demon',
        ability: '',
        id: '',
        power: 0,
        currentPower: 0,
        energy: 0,
        currentEnergy: 0,
        status: ECardStatus.ON_DECK,
      },
    ];
    dispatch(startGameAction(cards));
  });
  return (
    <>
      <Head>
        <title>Solo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PlayingTemplate />
    </>
  );
};

export default Home;
