import { Button } from '@components/common';
import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>Nextjs With Million</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <div className="flex flex-row">
          <div className="flex-1 h-16 bg-red-200">1</div>
          <div className="flex-1 h-16 bg-red-200">2</div>
          <div className="flex-1 h-16 bg-red-200">
            <Button />
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
