import Head from 'next/head';
import Link from 'next/link';

import { DATA_GAMES } from '@common/data/games.data';

const Home = () => {
  return (
    <>
      <Head>
        <title>Solo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-4">
        {DATA_GAMES.map((game) => (
          <Link key={game.name} href={`/games/${game.url}`}>
            <div>
              <span>{game.name}</span>
            </div>
          </Link>
        ))}
      </div>
    </>
  );
};

export default Home;
