import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.scss";

const Main = () => {
  const [count, setCount] = useState(0);
  return (
    <main className={styles.main}>

      <button onClick={() => setCount(count + 1)}>Count is {count}</button>
    </main>
  );
};

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs With Million</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
